language: minimal
services:
  - docker
env:
  - TAG=1
  - TAG=2
script:
  - cd $TAG
  - docker build --no-cache --pull -t wisvch/spring-boot-base:$TAG -t quay.io/wisvch/spring-boot-base:$TAG .
deploy:
  - provider: script
    script: >-
      sh -c '
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      echo pushing to wisvch/spring-boot-base:$TAG;
      docker push wisvch/spring-boot-base:$TAG;
      '
    on:
      branch: master
  - provider: script
    script: >-
      sh -c '
      docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io;
      echo pushing to quay.io/wisvch/spring-boot-base:$TAG;
      docker push quay.io/wisvch/spring-boot-base:$TAG;
      '
    on:
      branch: master
notifications:
  email: false
  slack:
    rooms:
      secure: EyOT1RGqAOAaCtsN8EBZAXziJPej4Cty+lqsbcCqyIL/gfJixH+iChZkloL07e5b0x5B/vDoH0SAOf9L4fEojx6ysP1qyUDGSeBh6LXC0+YIVrjCZRvleoVDSy1rAIITRJrJBxVE0YOLugQUzjFH5nOISFWfNPDSV9uAxXz7PKjdfD2+9x2Ow7CYBbm6XUMgjUsIdEWXKDHnVUv74AK+hrnr2VAenxWyYNPlIaNThZqaHCCsPhWcMryZO5m/Nx1Pp0lPpSqDFDrngkFIQ/tYQklL/Jtd8wuyn3nQyp9tWWtyaXEd0uDkcWNh7g7HcdnqmMIYxHg5OIaGdlymrIc/a/HPKy86dS2wABsOMOESMBzX9SpqSPNGR7LsYbolC6DWfAoMOfs7817ENpw/Qe+lpEGOgB4rI5SPvrbFdTIjPvadlmwBGnv42mWmK+B7RbFIkXxp2UtGwSVIckdiPsE6FEgw7aNcJ2UhJ6FR3UiD0UaXI0zI8kD9xD+nodm2e2FraD3Ktq/WKdRdKAZeUivPeLW772Zj9ePpVaiT1pwA9SHQfv7yory/6pHh00cRubzWgXX1ia/pFh31UN4Ac9EOQcJEZyLbmNS3O+uI4gkdOWuVLzKlcWlDjdyxjCZ/rC9N5QE5tXLKDMxzQMJDJLCU8bGslPqChpJeEDL7GoNu0bg=
