name: Docker
on:
  push:
jobs:
  buildDockerImage:
    name: Build Docker image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [1, 2.1, 2.2]
    steps:
    - name: Check out code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: wisvch/docker-spring-boot-base/${{ matrix.tag }}
        path: ${{ matrix.tag }}
        tags: latest
        push: ${{ github.ref == 'refs/heads/master' }}
