name: Docker
on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '54 4 2 * *'
jobs:
  buildDockerImage:
    name: Build Docker image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ["1", "2.1", "2.5.5"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.tag }}
        tags: |
          ghcr.io/wisvch/spring-boot-base:${{ matrix.tag }}
          wisvch/spring-boot-base:${{ matrix.tag }}
        push: ${{ github.ref == 'refs/heads/master' }}
