name: Docker
on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '54 2 2 * *'
jobs:
  buildDockerImage:
    name: Build Docker image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [1, 2.1]
    steps:
    - name: Check out code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: wisvch/spring-boot-base
        path: ${{ matrix.tag }}
        tags: ${{ matrix.tag }}
        push: ${{ github.ref == 'refs/heads/master' }}
